import { router } from "expo-router";
import { Pressable, Text, View } from "react-native";

import { AppScreen, Badge, Card, Header, Metric, PageScroll, PrimaryButton, SectionTitle } from "@/src/components/ui";
import { money, useMockData } from "@/src/data/mock-store";

export default function FinanceScreen() {
  const { customers, payments, customerBalance, cancelPayment } = useMockData(); const received = payments.filter((item) => !item.canceled).reduce((sum, item) => sum + item.amount, 0); const open = customers.reduce((sum, item) => sum + customerBalance(item.id), 0);
  return <AppScreen tab="Financeiro"><Header title="Financeiro" /><PageScroll className="pt-4"><View className="flex-row gap-2"><Card className="flex-1"><Metric label="Recebido" value={money(received)} tone="text-brand-700" /></Card><Card className="flex-1"><Metric label="Em aberto" value={money(open)} tone="text-amber-700" /></Card></View><SectionTitle title="Clientes a receber" />{customers.filter((item) => customerBalance(item.id) > 0).map((customer) => <Card className="mb-3" key={customer.id}><View className="flex-row items-center"><View className="flex-1"><Text className="font-bold text-ink">{customer.tradeName}</Text><Text className="mt-1 text-xs text-neutral-500">Saldo em aberto</Text></View><Text className="font-bold text-ink">{money(customerBalance(customer.id))}</Text></View></Card>)}<SectionTitle title="Pagamentos recentes" />{payments.map((payment) => <Card className="mb-3" key={payment.id}><View className="flex-row items-center"><View className="flex-1"><Text className="font-bold text-ink">{payment.number}</Text><Text className="mt-1 text-xs text-neutral-500">{payment.method} • {payment.paidAt}</Text></View><View className="items-end"><Text className="font-bold text-brand-700">{money(payment.amount)}</Text>{payment.canceled ? <Badge label="Cancelado" tone="red" /> : <Pressable className="mt-2" onPress={() => cancelPayment(payment.id)}><Text className="text-xs font-bold text-danger">Cancelar</Text></Pressable>}</View></View></Card>)}<View className="mt-4 flex-row gap-3"><View className="flex-1"><PrimaryButton label="Pagamento" icon="cash" onPress={() => router.push("/finance/payment-general")} /></View><View className="flex-1"><PrimaryButton label="Relatórios" icon="bar-chart" secondary onPress={() => router.push("/finance/reports")} /></View></View></PageScroll></AppScreen>;
}
