import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { Alert, Pressable, Text, View } from "react-native";

import { AppScreen, Card, Field, Header, Metric, PageScroll, PrimaryButton, SectionTitle } from "@/src/components/ui";
import { money, type OrderItem, useMockData } from "@/src/data/mock-store";

export default function OrderFormScreen() {
  const params = useLocalSearchParams<{ id?: string; customerId?: string }>(); const { customers, products, orders, resolvePrice, saveOrder } = useMockData(); const current = orders.find((item) => item.id === params.id);
  const [customerId, setCustomerId] = useState(current?.customerId ?? params.customerId ?? customers[0]?.id ?? ""); const [items, setItems] = useState<OrderItem[]>(current?.items ?? []); const [deliveryDate, setDeliveryDate] = useState(current?.deliveryDate ?? "15/07/2026"); const [dueDate, setDueDate] = useState(current?.dueDate ?? "22/07/2026"); const [notes, setNotes] = useState(current?.notes ?? "");
  const total = items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0);
  function addProduct(productId: string) { const product = products.find((item) => item.id === productId); if (!product) return; setItems((list) => { const found = list.find((item) => item.productId === productId); return found ? list.map((item) => item.productId === productId ? { ...item, quantity: item.quantity + 1 } : item) : [...list, { id: `item-${Date.now()}`, productId, productName: product.name, quantity: 1, unitPrice: resolvePrice(customerId, productId) }]; }); }
  function changeQuantity(productId: string, delta: number) { setItems((list) => list.map((item) => item.productId === productId ? { ...item, quantity: Math.max(0, item.quantity + delta) } : item).filter((item) => item.quantity > 0)); }
  function submit() { if (!customerId || !items.length) return Alert.alert("Pedido incompleto", "Selecione um cliente e adicione ao menos um produto."); const id = saveOrder({ id: params.id, customerId, status: current?.status ?? "Rascunho", deliveryDate, dueDate, notes, items, createdAt: current?.createdAt ?? new Date().toLocaleDateString("pt-BR") }); router.replace({ pathname: "/order-details", params: { id } }); }
  return <AppScreen><Header title={current ? "Editar pedido" : "Novo pedido"} back /><PageScroll className="pt-5"><Text className="mb-2 text-xs font-semibold text-neutral-700">Cliente *</Text><View className="mb-4 flex-row flex-wrap gap-2">{customers.map((customer) => <Pressable className={`rounded-full px-3 py-2 ${customerId === customer.id ? "bg-brand-700" : "bg-white"}`} key={customer.id} onPress={() => setCustomerId(customer.id)}><Text className={`text-xs ${customerId === customer.id ? "text-white" : "text-ink"}`}>{customer.tradeName}</Text></Pressable>)}</View><SectionTitle title="Itens" action="Toque para adicionar" /><View className="mb-4 flex-row flex-wrap gap-2">{products.map((product) => <Pressable className="rounded-xl bg-white px-3 py-3" key={product.id} onPress={() => addProduct(product.id)}><Text className="text-xs font-semibold">{product.icon} {product.name}</Text></Pressable>)}</View>{items.map((item) => <Card className="mb-3" key={item.id}><View className="flex-row items-center"><View className="flex-1"><Text className="font-bold text-ink">{item.productName}</Text><Text className="text-xs text-neutral-500">{money(item.unitPrice)} cada</Text></View><Pressable className="p-3" onPress={() => changeQuantity(item.productId, -1)}><Text>−</Text></Pressable><Text className="font-bold">{item.quantity}</Text><Pressable className="p-3" onPress={() => changeQuantity(item.productId, 1)}><Text>+</Text></Pressable></View></Card>)}<Field label="Data de entrega" value={deliveryDate} onChangeText={setDeliveryDate} /><Field label="Vencimento" value={dueDate} onChangeText={setDueDate} /><Field label="Observações" value={notes} onChangeText={setNotes} multiline /><Card><Metric label="Total do pedido" value={money(total)} tone="text-brand-700" /></Card><View className="mt-5"><PrimaryButton label="Salvar pedido" icon="checkmark" onPress={submit} /></View></PageScroll></AppScreen>;
}
