import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { Alert, Text, View } from "react-native";

import { AppScreen, Card, Field, Header, PageScroll, PrimaryButton, SectionTitle } from "@/src/components/ui";
import { money, parseMoney, useMockData } from "@/src/data/mock-store";

export default function PaymentGeneralScreen() {
  const { customerId = "c1" } = useLocalSearchParams<{ customerId?: string }>(); const { customers, orders, customerBalance, orderTotal, orderPaid, savePayment } = useMockData(); const customer = customers.find((item) => item.id === customerId); const balance = customerBalance(customerId); const openOrders = orders.filter((order) => order.customerId === customerId && orderTotal(order) > orderPaid(order.id)); const [amount, setAmount] = useState(money(balance)); const [method, setMethod] = useState("Pix"); const [date, setDate] = useState(new Date().toLocaleDateString("pt-BR"));
  function submit() { const value = parseMoney(amount); if (value <= 0 || value > balance) return Alert.alert("Valor inválido", `O pagamento não pode superar ${money(balance)}.`); const selected: string[] = []; let remaining = value; openOrders.forEach((order) => { if (remaining > 0) { selected.push(order.id); remaining -= Math.max(orderTotal(order) - orderPaid(order.id), 0); } }); const id = savePayment({ customerId, amount: value, method, paidAt: date, notes: "Pagamento geral", orderIds: selected }); router.replace({ pathname: "/payment-receipt", params: { id } }); }
  return <AppScreen><Header title="Pagamento do cliente" back /><PageScroll className="pt-5"><Card><Text className="text-xs text-neutral-500">{customer?.tradeName}</Text><Text className="mt-1 text-xl font-bold text-ink">Saldo em aberto: {money(balance)}</Text></Card><View className="mt-5"><Field label="Valor recebido *" value={amount} onChangeText={setAmount} keyboardType="decimal-pad" /><Field label="Forma de pagamento" value={method} onChangeText={setMethod} /><Field label="Data do pagamento" value={date} onChangeText={setDate} /></View><SectionTitle title="Débitos em aberto" action="Mais antigos primeiro" /><Card>{openOrders.map((order, i) => <View className={`flex-row justify-between py-3 ${i < openOrders.length - 1 ? "border-b border-neutral-100" : ""}`} key={order.id}><Text className="text-xs font-bold text-ink">{order.number}</Text><Text className="text-sm font-bold text-brand-700">{money(orderTotal(order) - orderPaid(order.id))}</Text></View>)}</Card><View className="mt-5"><PrimaryButton label="Confirmar pagamento" icon="checkmark-circle" onPress={submit} /></View></PageScroll></AppScreen>;
}
