import { Ionicons } from "@expo/vector-icons";
import { router, useLocalSearchParams } from "expo-router";
import { Alert, Pressable, Text, View } from "react-native";

import { AppScreen, Badge, Card, Header, Metric, PageScroll, PrimaryButton, SectionTitle } from "@/src/components/ui";
import { money, useMockData } from "@/src/data/mock-store";

export default function OrderDetailsScreen() {
  const { id = "o2" } = useLocalSearchParams<{ id?: string }>(); const { orders, customers, orderTotal, orderPaid, deleteOrder, updateOrderStatus } = useMockData(); const order = orders.find((item) => item.id === id);
  if (!order) return <AppScreen><Header title="Pedido" back /><View className="flex-1 items-center justify-center"><Text>Pedido não encontrado.</Text></View></AppScreen>;
  const customer = customers.find((item) => item.id === order.customerId); const total = orderTotal(order); const paid = orderPaid(id);
  function remove() { Alert.alert("Excluir pedido", "O pedido será removido desta sessão.", [{ text: "Cancelar" }, { text: "Excluir", style: "destructive", onPress: () => { deleteOrder(id); router.replace("/orders"); } }]); }
  return <AppScreen><Header title={order.number} back action={<Pressable onPress={() => router.push({ pathname: "/orders/form", params: { id } })}><Ionicons name="pencil" size={20} color="#17201B" /></Pressable>} /><PageScroll className="pt-5"><View className="flex-row items-center justify-between"><Badge label={order.status} tone={order.status === "Cancelado" ? "red" : "green"} /><Text className="text-xs text-neutral-500">Criado em {order.createdAt}</Text></View><Card className="mt-4"><Text className="font-bold text-ink">{customer?.tradeName}</Text><Text className="mt-1 text-xs text-neutral-500">{customer?.phone}</Text></Card><SectionTitle title="Itens do pedido" /><Card>{order.items.map((item, i) => <View className={`flex-row items-center py-3 ${i < order.items.length - 1 ? "border-b border-neutral-100" : ""}`} key={item.id}><Text className="flex-1 text-xs font-semibold text-ink">{item.productName}</Text><Text className="w-14 text-xs text-neutral-500">{item.quantity}</Text><Text className="text-xs font-bold text-ink">{money(item.quantity * item.unitPrice)}</Text></View>)}</Card><Card className="mt-3"><View className="flex-row"><Metric label="Total" value={money(total)} /><Metric label="Recebido" value={money(paid)} /><Metric label="Saldo" value={money(Math.max(total - paid, 0))} tone="text-brand-700" /></View></Card>
    <Text className="mb-2 mt-5 text-xs font-semibold text-neutral-700">Alterar status</Text><View className="mb-5 flex-row flex-wrap gap-2">{["Rascunho", "Confirmado", "Em produção", "Pronto", "Entregue", "Cancelado"].map((status) => <Pressable className={`rounded-full px-3 py-2 ${order.status === status ? "bg-brand-700" : "bg-white"}`} key={status} onPress={() => updateOrderStatus(id, status)}><Text className={`text-xs ${order.status === status ? "text-white" : "text-ink"}`}>{status}</Text></Pressable>)}</View>
    <View className="flex-row gap-3"><View className="flex-1"><PrimaryButton label="Pagamento" icon="cash" onPress={() => router.push({ pathname: "/finance/payment-order", params: { orderId: id } })} /></View><View className="flex-1"><PrimaryButton label="Comprovante" icon="document-text" secondary onPress={() => router.push("/orders/receipt")} /></View></View><View className="mt-3"><PrimaryButton label="Repetir pedido" icon="repeat" secondary onPress={() => router.push({ pathname: "/orders/repeat", params: { id } })} /></View><Pressable className="mt-5 py-3" onPress={remove}><Text className="text-center font-bold text-danger">Excluir pedido</Text></Pressable>
  </PageScroll></AppScreen>;
}
